CREATE SCHEMA WALLET_CONTROL;

CREATE SEQUENCE WALLET_CONTROL.ID_WALLET_SEQ;

CREATE TABLE WALLET_CONTROL.WALLET (
ID_WALLET INTEGER NOT NULL DEFAULT NEXTVAL ('WALLET_CONTROL.ID_WALLET_SEQ'),
OWNER_NAME CHARACTER VARYING(50) NOT NULL,
WALLET_VALUE NUMERIC(10,2) NOT NULL,
PRIMARY KEY (ID_WALLET)
);

CREATE SEQUENCE WALLET_CONTROL.ID_PAYMENT_SEQ;

CREATE TABLE WALLET_CONTROL.PAYMENT (
ID_PAYMENT INTEGER NOT NULL DEFAULT NEXTVAL ('WALLET_CONTROL.ID_PAYMENT_SEQ'),
AMOUNT NUMERIC(10,2) NOT NULL,
PAYMENT_DATE DATE NOT NULL,
ID_WALLET INTEGER, 
PRIMARY KEY (ID_PAYMENT),
FOREIGN KEY (ID_WALLET) REFERENCES WALLET_CONTROL.WALLET(ID_WALLET)
);